version: '3.8'
services: 
  # jaeger-server:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "16686:16686"
  #     - "14268"
  #     - "14250"

  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
      
  collector:
    #build:
    #  context: ../opentelemetry-collector-contrib
    #  dockerfile: examples/tracing/Dockerfile
    image: otel/opentelemetry-collector-contrib-dev
    command: --config /config/collector-config.yaml
    environment:
      - AWS_PROFILE=default
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    ports:
      - "55680:55680"
      - "55681:55681"
    volumes:
      - ./collector-config.yaml:/config/collector-config.yaml
      - ~/.aws:/root/.aws
    depends_on:
      - zipkin-server
      # - jaeger-server
